# fly.toml app configuration file generated for soundsampler on 2025-01-04T16:46:34+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'soundsampler'
primary_region = 'nrt'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_DEBUG = 'true'
  APP_ENV = 'production'
  APP_FAKER_LOCALE = 'ja_JP'
  APP_FALLBACK_LOCALE = 'en'
  APP_KEY = 'base64:ECx9EMUN0aQRApwiL9F0OLJ+xWKNr/i7hG1N0zjDZmQ='
  APP_LOCALE = 'ja'
  APP_MAINTENANCE_DRIVER = 'file'
  APP_NAME = 'SoundSampler'
  APP_TIMEZONE = 'Asia/Tokyo'
  APP_URL = 'http://localhost'
  DB_CONNECTION = 'pgsql'
  DB_DATABASE = 'laravel'
  DB_HOST = 'pgsql'
  DB_PASSWORD = 'password'
  DB_PORT = '5432'
  DB_USERNAME = 'sail'
  PGADMIN_EMAIL = 'rfb0920@gmail.com'
  PGADMIN_PASSWORD = 'up.K_aZKkD4E-*o'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DOMAIN = 'null'
  SESSION_DRIVER = 'cookie'
  SESSION_ENCRYPT = 'false'
  SESSION_LIFETIME = '120'
  SESSION_PATH = '/'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
